### ISSUE TITLE
installation mac os. issue

### ISSUE THREAD

**Issue by nickbrave777** [miguelmota/go-ethereum-hdwallet#11]
Im getting an error while installing:

robert@Roberts-MacBook-Air gocourse % go get -u github.com/miguelmota/go-ethereum-hdwallet
github.com/miguelmota/go-ethereum-hdwallet
../src/github.com/miguelmota/go-ethereum-hdwallet/hdwallet.go:494:17: key.Child undefined (type *hdkeychain.ExtendedKey has no field or method Child)

**Comment by zhaorui20005** [comment]
Have you solved this yet? I got the same in mac.

**Comment by ahyuen75** [comment]
same issue on Mac M1

**Comment by pjecoin** [comment]
Just update  your go version,  I used. go version go1.16beta1 darwin/amd64

**Comment by nickbrave777** [comment]
Just update your go version, I used. go version go1.16beta1 darwin/amd64

**Comment by zhaorui20005** [comment]
> Just update your go version, I used. go version go1.16beta1 darwin/amd64

Thanks.But I run brew update and brew upgrade go, only updated my go from 1.15.6 to 1.15.7.
And I still got the same msg when I import "github.com/miguelmota/go-ethereum-hdwallet" to run my own go program. But I can run go test in go-ethereum-hdwallet dir to run the test without errors.

**Comment by miguelmota** [comment]
You may try installing latest Go from binary release:

```bash
wget https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.16.2.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
```

**Comment by miguelmota** [comment]
Latest version of library should work now since vendor packages have been updated.

<img width="570" alt="Screen Shot 2021-03-19 at 3 09 15 PM" src="https://user-images.githubusercontent.com/168240/111847220-9a160000-88c5-11eb-9011-71be3405cfbb.png">
