### ISSUE TITLE
Wallet is not an accounts.Wallet anymore

### ISSUE THREAD

**Issue by ggwpez** [miguelmota/go-ethereum-hdwallet#15]
After my last MR (#13) was merged, i noticed that `Wallet` does not fulfill the `accounts.Wallet` interface from geth anymore.  
This was not indented but slipped under the radar.  

I will prepare another MR to fix it. The *baseFee* is not even used for signing but to verify the signature, which can also be done without it.  
So my next MR (#16) will effectively revert #13, get rid of the `AsMessage` function by using `Sender` instead and add a type assertion.  

Sorry for the inconvenience :pray:

**Comment by miguelmota** [comment]
Ah I see, understood 👍

Mistake on my end as well for not verifying that new changes continue to implement the interface. 

The latest PR looks good and I don't see any problems with merging it.

Thanks again @ggwpez

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/go-ethereum-hdwallet/pull/16
