### ISSUE TITLE
Large go.sum file

### ISSUE THREAD

**Issue by blkmlk** [miguelmota/go-ethereum-hdwallet#17]
Hello! The go.sum file of the repo has a lot of unused packages, importing the code also brings all of them. It would be great if you fixed it. Thanks

**Comment by miguelmota** [comment]
Hi @blkmlk! I think it's because this package imports go-ethereum, and go-ethereum has a lot of dependencies. Wiping the vendor directory and running `go mod tidy` didn't have any effect on reducing go.sum file
