### ISSUE TITLE
duplicate symbol (macos)

### ISSUE THREAD

**Issue by benjyz** [miguelmota/go-ethereum-hdwallet#2]
some linker issue under MacOS

```
$ go run example.go 
# command-line-arguments
/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
duplicate symbol _secp256k1GoPanicError in:
```

**Comment by miguelmota** [comment]
@benjyz interesting, haven't seen that before and I'm on macOS as well. I reran `dep ensure` so everything should be up to date. The tests are also passing on travis, so it's an issue out of the scope of this package. 

Some things you can try:
- git clone the repo
- delete `github.com/ethereum/go-ethereum` from `vendor/`
- install the latest go-ethereum `go get -u github.com/ethereum/go-ethereum`

If still having the same issue then report to go-ethereum

**Comment by miguelmota** [comment]
Please reopen issue if problem persists
