### ISSUE TITLE
BTC private key to address and balance check

### ISSUE THREAD

**Issue by Handsomekaizer** [miguelmota/go-ethereum-hdwallet#26]
I just stumbled on these your GitHub repo I was looking for a program that will help me convert my compressed Bitcoin private key to address and check the balance. Could you please help me update or create a python program that will help me convert my compressed private key to address and check the balance. The reason I needed this was to scan through a massive private key txt file and see if I can find my missing 6 characters private key. Please help me if I recover the wallet I will donate some BTC to you. Thanks

**Comment by miguelmota** [comment]
Unfortunately I can't help with this request.

Closing as out of scope.
