### ISSUE TITLE
Allow mnemonic with password

### ISSUE THREAD

**Issue by pnowosie** [miguelmota/go-ethereum-hdwallet#28]
Hello @miguelmota 

I think this awesome library will benefit having optional password in seed calculation. 
This is smth I need in my code anyway, so I could open a PR here as well if you would like. 

I'm thinking of extending this function:
https://github.com/miguelmota/go-ethereum-hdwallet/blob/dca85a91a62cfd173ef35b8609ed7b0ae1e4aafb/hdwallet.go#L495

e.g. to keep backward compatibility
```go
func NewSeedFromMnemonic(mnemonic string, passOpt ...string) ([]byte, error) {
	if mnemonic == "" {
		return nil, errors.New("mnemonic is required")
	}

	var password = ""
	if len(passOpt) > 0 {
		password = passOpt[0]
	}

	return bip39.NewSeedWithErrorChecking(mnemonic, password)
}
```

What do you think?

**Comment by miguelmota** [comment]
Hi @pnowosie, I think adding the password parameter as you suggested is a good idea. Happy to merge a PR!

**Comment by pnowosie** [comment]
Hello @miguelmota just letting to know that PR is ready (in case GH failed to notify you).

(sorry to bother you - bumping this lib version would make my life easier ;)

**Comment by miguelmota** [comment]
@pnowosie thanks for the ping; reviewed and merged!
