### ISSUE TITLE
too many dependencies 

### ISSUE THREAD

**Issue by fadeAce** [miguelmota/go-ethereum-hdwallet#4]
github.com/btcsuite/btcd/chaincfg
like go btc implementation 
it cause a huge binary after compile , could it apply a prune dependencies to the slightest ?

**Comment by fadeAce** [comment]
I mean why I have to down load btc related when doing eth wallet

**Comment by miguelmota** [comment]
@fadeAce I agree that it's not ideal but the btcsuite package has the best hdkeychain implementation in Go. This package is wrapper around the hdkeychain that implements the Wallet interface from go-ethereum. I guess the btc packages can be copied over and renamed

**Comment by miguelmota** [comment]
Looks like 1.2mB out of the 1.7mB uncompiled size is from the [secp256k1](https://github.com/btcsuite/btcd/blob/master/btcec/secp256k1.go) go implementation. 

Closing issue since the dependencies are required.
