### ISSUE TITLE
Missing method implementations from the accounts.Wallet interface

### ISSUE THREAD

**Issue by drdgvhbh** [miguelmota/go-ethereum-hdwallet#5]
The wallet seems to be missing the following methods. Using `go-ethereum 1.9`

* [SignData](https://github.com/ethereum/go-ethereum/blob/master/accounts/accounts.go#L113)
* [SignDataWithPassphrase](https://github.com/ethereum/go-ethereum/blob/master/accounts/accounts.go#L119)
* [SignText](https://github.com/ethereum/go-ethereum/blob/master/accounts/accounts.go#L132)

**Comment by miguelmota** [comment]
@drdgvhbh Thanks for reporting. This package is in dire need of an update. Will get to it soon but also happy to merge a PR

**Comment by miguelmota** [comment]
Closed via https://github.com/miguelmota/go-ethereum-hdwallet/commit/7e0d9e8299bd27dfe5c4870ccfb7441a93840f87
