### ISSUE TITLE
go.mod parse error, module name unmatch

### ISSUE THREAD

**Issue by qiluge** [miguelmota/go-ethereum-hdwallet#9]
why the module name is defined  as ```module github.com/immutability-io/go-ethereum-hdwallet
``` in your go.mod ? I think it should be ```module github.com/miguelmota/go-ethereum-hdwallet```

**Comment by miguelmota** [comment]
Closed via https://github.com/miguelmota/go-ethereum-hdwallet/commit/abf3d7f7f00ced146db856590502a3ceaea5954c
